
stages:
  - run-test
  - trigger-test

build:
  # Uses official Cypress docker image for dependencies
  # https://docs.cypress.io/guides/continuous-integration/introduction#Official-Cypress-Docker-Images
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: run-test
  
  script:
    - npm i

    #run tests
    - npx cypress run --record --browser chrome